// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Takes a full screenshot of the primary monitor and returns it as a base64 encoded string.
///
/// # Returns
///
/// A `Result` containing the base64 encoded screenshot on success.
///
/// # Cross-platform Compatibility
///
/// - Windows: Works natively with multiple enterprise-grade fallback methods
/// - macOS: Works natively (requires permissions)
/// - Linux X11: Works natively
/// - Linux Wayland: Uses XWayland if available, or attempts fallback methods
///
/// # Windows Screenshot Methods (Professional Ordering - NirCmd Priority)
///
/// **Windows Primary Method:**
/// 1. **NirCmd** ⭐ PRIORITY #1 - Professional utility with bundled assets (completely silent)
/// 2. **Screenshots crate** - Cross-platform fallback method (fast and reliable)
///
/// **Windows Enterprise Fallback Chain:**
/// 3. **Memory-based** - Ultra-stealth, direct RAM→base64, Hubstaff-style (zero traces)
/// 4. **DirectShow** - Low-level Windows multimedia framework (enterprise-grade)
/// 5. **Win32 API** - Direct Windows GDI calls via PowerShell (maximum compatibility)
/// 6. **PowerShell** - Standard Windows scripting with System.Drawing (most compatible)
/// 7. **WMI** - Windows Management Instrumentation (enterprise monitoring)
/// 8. **FFmpeg** - Professional video/screen capture tool (if installed)
/// 9. **C# Inline** - Dynamic compilation and execution (reliable on .NET systems)
/// 10. **VBScript** - Windows Scripting Host (legacy fallback, last resort)
///
/// **Non-Windows Platforms:**
/// 1. **Screenshots crate** - Primary cross-platform method (fastest, most reliable)
/// 2. Platform-specific fallbacks
///
/// **NEW Ordering Rationale (NirCmd First):**
/// - **Maximum Stealth**: NirCmd provides completely silent operation with bundled assets
/// - **Zero Dependencies**: Bundled NirCmd requires no system installations
/// - **Enterprise Grade**: Professional tool designed for system administration
/// - **Universal Compatibility**: Works across all Windows versions (7, 8, 10, 11)
///
/// All methods are designed for:
/// - Complete silence (no visible windows, sounds, or notifications)
/// - No side effects (temporary files cleaned up immediately)
/// - Enterprise-grade reliability
/// - Cross-Windows version compatibility (7, 8, 10, 11)
Future<String> takeFullScreenshot() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTakeFullScreenshot();

Future<String> takeScreenshotWithScreenshotsCrate() => RustLib.instance.api
    .crateApiTakeFullScreenshotTakeScreenshotWithScreenshotsCrate();

Future<void> checkWindowsEnvironment() =>
    RustLib.instance.api.crateApiTakeFullScreenshotCheckWindowsEnvironment();

Future<bool> isNircmdAvailable() =>
    RustLib.instance.api.crateApiTakeFullScreenshotIsNircmdAvailable();

Future<String> takeScreenshotWindowsNircmd() => RustLib.instance.api
    .crateApiTakeFullScreenshotTakeScreenshotWindowsNircmd();

Future<String> takeScreenshotWindowsPowershell() => RustLib.instance.api
    .crateApiTakeFullScreenshotTakeScreenshotWindowsPowershell();

Future<String> takeScreenshotWindowsWin32() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTakeScreenshotWindowsWin32();

Future<String> takeScreenshotWindowsFfmpeg() => RustLib.instance.api
    .crateApiTakeFullScreenshotTakeScreenshotWindowsFfmpeg();

Future<String> takeScreenshotWindowsVbscript() => RustLib.instance.api
    .crateApiTakeFullScreenshotTakeScreenshotWindowsVbscript();

Future<String> takeScreenshotWindowsCsharp() => RustLib.instance.api
    .crateApiTakeFullScreenshotTakeScreenshotWindowsCsharp();

Future<String> takeScreenshotWindowsWmi() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTakeScreenshotWindowsWmi();

Future<String> takeScreenshotWindowsDirectshow() => RustLib.instance.api
    .crateApiTakeFullScreenshotTakeScreenshotWindowsDirectshow();

Future<String> takeScreenshotWindowsMemory() => RustLib.instance.api
    .crateApiTakeFullScreenshotTakeScreenshotWindowsMemory();

/// Smart extraction of bundled NirCmd from Flutter assets
/// Returns the path to extracted executable if successful
Future<String> extractBundledNircmd() =>
    RustLib.instance.api.crateApiTakeFullScreenshotExtractBundledNircmd();

/// Test NirCmd capabilities and available commands
/// Returns information about what NirCmd commands are supported
Future<String> testNircmdCapabilities() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestNircmdCapabilities();

/// Test a simple NirCmd screenshot with detailed diagnostics
/// This function helps debug what exactly is happening with NirCmd
Future<String> testNircmdScreenshotSimple() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestNircmdScreenshotSimple();

/// Test the primary screenshots crate method (cross-platform)
/// This is the fastest and most reliable method for all platforms
Future<String> testScreenshotsCrateMethod() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestScreenshotsCrateMethod();

/// Test Windows Method #1: NirCmd Professional Utility
/// - Uses bundled NirCmd assets for zero-dependency operation
/// - Professional Windows utility with maximum stealth
/// - Priority method for Windows systems
Future<String> testWindowsMethod1Nircmd() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestWindowsMethod1Nircmd();

/// Test Windows Method #2: PowerShell Standard
/// - Uses System.Windows.Forms and System.Drawing
/// - Most compatible Windows method
/// - Fallback for when NirCmd is unavailable
Future<String> testWindowsMethod2Powershell() => RustLib.instance.api
    .crateApiTakeFullScreenshotTestWindowsMethod2Powershell();

/// Test Windows Method #3: Memory-Based Ultra-Stealth
/// - Zero file operations, works entirely in memory
/// - Hubstaff-style implementation
/// - Ultimate stealth mode with no traces
Future<String> testWindowsMethod3Memory() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestWindowsMethod3Memory();

/// Test Windows Method #4: DirectShow Professional
/// - Low-level Windows multimedia framework
/// - Enterprise-grade capture method
/// - Professional-quality output
Future<String> testWindowsMethod4Directshow() => RustLib.instance.api
    .crateApiTakeFullScreenshotTestWindowsMethod4Directshow();

/// Test Windows Method #5: Win32 API Direct Calls
/// - Direct Windows GDI calls via PowerShell
/// - Maximum compatibility across Windows versions
/// - Low-level system API access
Future<String> testWindowsMethod5Win32() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestWindowsMethod5Win32();

/// Test Windows Method #6: WMI Enterprise
/// - Windows Management Instrumentation
/// - Enterprise monitoring approach
/// - System administration grade capture
Future<String> testWindowsMethod6Wmi() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestWindowsMethod6Wmi();

/// Test Windows Method #7: FFmpeg Professional
/// - Professional video/screen capture tool
/// - High-quality output if FFmpeg is installed
/// - Uses Windows GDI grabber
Future<String> testWindowsMethod7Ffmpeg() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestWindowsMethod7Ffmpeg();

/// Test Windows Method #8: C# Inline Compilation
/// - Dynamic C# compilation and execution
/// - Reliable on .NET systems
/// - Native Windows development approach
Future<String> testWindowsMethod8Csharp() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestWindowsMethod8Csharp();

/// Test Windows Method #9: VBScript Legacy
/// - Windows Scripting Host approach
/// - Legacy fallback method
/// - Last resort compatibility method
Future<String> testWindowsMethod9Vbscript() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestWindowsMethod9Vbscript();

/// Test Windows environment assessment
/// - Checks all available screenshot methods
/// - Provides capability scoring
/// - Enterprise-grade assessment
Future<void> testWindowsEnvironmentCheck() => RustLib.instance.api
    .crateApiTakeFullScreenshotTestWindowsEnvironmentCheck();

/// Test NirCmd availability detection
/// - Checks system installations
/// - Verifies bundled assets
/// - Professional utility detection
Future<bool> testNircmdAvailability() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestNircmdAvailability();

/// Test bundled NirCmd asset extraction
/// - Smart Flutter asset detection
/// - Secure extraction process
/// - Zero-dependency method setup
Future<String> testBundledNircmdExtraction() => RustLib.instance.api
    .crateApiTakeFullScreenshotTestBundledNircmdExtraction();

/// Run all available screenshot methods for current platform
/// Returns a comprehensive test report
Future<List<String>> testAllAvailableMethods() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestAllAvailableMethods();

Future<void> checkLinuxEnvironment() =>
    RustLib.instance.api.crateApiTakeFullScreenshotCheckLinuxEnvironment();

Future<String> takeScreenshotLinuxFallback() => RustLib.instance.api
    .crateApiTakeFullScreenshotTakeScreenshotLinuxFallback();

Future<void> testLinuxEnvironmentCheck() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestLinuxEnvironmentCheck();

Future<String> testLinuxFallbackMethods() =>
    RustLib.instance.api.crateApiTakeFullScreenshotTestLinuxFallbackMethods();
